### ISSUE TITLE
Webアプリで開発する？Electronで開発する？

### ISSUE THREAD

**Issue by aokashi** [WWAWing/WWAMaker#1]
これまで[WWA Wing マップ作成ツール](https://github.com/WWAWing/WinWwaWingmk)を開発していましたが、古いアプリケーションをベースに保守改良するにはもう限界が近いことから、WWAMaker の開発を再開しようと考えています。

その際、Webアプリとしてブラウザ上で動作するように開発しようか、デスクトップアプリとして Electronで開発しようかどちらかを考えています。

最終的には、WWAのデータのフォーマットを公開して、スーパー正男のようにそれぞれの特徴を持った作成ツールができたらいいな・・・と思っていますが、課題はいくつかありそうです。

**Comment by aruneko** [comment]
技術選定をする上で、マルチプラットフォームで動かしたいのか、あるいはWindowsだけで動けばいいのかで候補技術が異なってくると思うのですが、現状はどう考えていますか？

**Comment by aruneko** [comment]
となるとだいたい以下の三択のような気がします。

- Electron
- JavaFX
- Web

簡単にメリットとデメリットを整理しておきます。

# Electron
## メリット
- 書き慣れたWeb技術を使って作れる
- ほとんどの場合でプラットフォーム依存コードを書く必要は無い
- テストプレイはやりやすい可能性大
    - そのままElectron内で処理しちゃえば良さそう

## デメリット
- ランタイムのファイルサイズがかなり大きい

# JavaFX
## メリット
- JVMさえ入っていればどこでも動く
- ほとんどの場合でプラットフォーム依存コードを書く必要は無い

## デメリット
- 生Javaは結構辛い
    - Kotlinか何かでwrapした方がよさそう
- Java11以降は標準に含まれなくなってしまった
- `.jar` ファイルの実行に抵抗感がある人がいるかも？

# Web
## メリット
- ブラウザだけあれば動く
- アップデートがあった際にユーザー側は何もしなくてOK

## デメリット
- VueやらReactやら色々あるので何か選ばなければならない
- IEサポート問題(できればサポートしたくない)
- ゲームのデバッグをどうする？
    - 画像はもちろん、効果音もアップロードできないとデバッグが辛いかも

**Comment by aokashi** [comment]
自分の考えの中だと、Electronで良いのかなと考えています。
ちなみに、ElectronでもWebアプリでも、ビューを扱うフレームワーク(今回だったらReact？Vue？)は導入予定です。

## JavaFX
WWA Wingと開発言語が統一できないため、扱いづらい。別途ランタイムが必要で不便なのもありそ
う。

## Web
ファイルの読込や保存を実装する場合が大変になりそう。

例えばローカルファイル。
マップデータファイルとイメージ画像ファイルの2つが必要になるのだが、それぞれ参照で選んで・・・となると手間が掛かってしまい、ユーザビリティは落ちる。
参照ボタン無しで実装できれば良いのですが・・・ブラウザの問題になりそう。

マップデータをクラウドストレージで扱えれば理想だが、整えるコストは大きいかもしれない？

**Comment by aokashi** [comment]
今の所マルチプラットフォームで動作することを前提としていますね。

**Comment by aokashi** [comment]
これから、 Electron を導入する際に発生する問題点について書こうと思います。

## ディレクトリ構成をどうするか？
- Electron ではメインプロセスとレンダラープロセスの2つのプロセスに対応したソースファイルを記述する必要がある
- 現在、 WWAMaker では monorepo の構成になっていて、メインプロセス用のパッケージとレンダラープロセス用のパッケージで分ければそれが理想だが、果たして実現可能なのか？
- もし分けることができない場合は `src` ディレクトリにメインプロセス用のディレクトリとレンダラープロセス用のディレクトリに分ける展開になると思われる
